








include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
    - "**/generated/**"
    - "lib/app/injection.config.dart"
    - "lib/l10n/**"

linter:
  
  
  
  
  
  
  
  
  
  
  rules:
    
    



